services:
    _defaults:
        autowire: true
        autoconfigure: true

    #Core listeners
    App\Listener\Core\PlayerListener:
        arguments:
            $playerIndexer: '@api.indexer.players'
            $teamIndexer: '@api.indexer.teams'
        tags:
            - { name: kernel.event_subscriber }

    App\Listener\Core\TeamListener:
        arguments:
            $teamIndexer: '@api.indexer.teams'
            $playerIndexer: '@api.indexer.players'
            $ladderIndexer: '@api.indexer.ladder'
            $membersIndexer: '@api.indexer.members'
        tags: { name: kernel.event_subscriber }

    App\Listener\Core\MemberListener:
        arguments:
            $teamIndexer: '@api.indexer.teams'
            $playerIndexer: '@api.indexer.players'
            $ladderIndexer: '@api.indexer.ladder'
            $membersIndexer: '@api.indexer.members'
        tags: { name: kernel.event_subscriber }

    App\Listener\Core\RegionListener:
        arguments:
            $playerIndexer: '@api.indexer.players'
            $ladderIndexer: '@api.indexer.ladder'
            $teamIndexer: '@api.indexer.teams'
        tags:
            - { name: kernel.event_subscriber }

    #League listeners
    App\Listener\LeagueOfLegends\PlayerListener:
        arguments:
            $playerIndexer: '@api.indexer.players'
            $ladderIndexer: '@api.indexer.ladder'
            $teamIndexer: '@api.indexer.teams'
        tags:
            - { name: kernel.event_subscriber }

    App\Listener\LeagueOfLegends\RankingListener:
        arguments:
            $playerIndexer: '@api.indexer.players'
            $ladderIndexer: '@api.indexer.ladder'
        tags:
            - { name: kernel.event_subscriber }

    App\Listener\LeagueOfLegends\SummonerNameListener:
        arguments:
            $playerIndexer: '@api.indexer.players'
            $summonerNameIndexer: '@api.indexer.summoner_names'
        tags:
            - { name: kernel.event_subscriber }

    App\Listener\LeagueOfLegends\RiotAccountListener:
        arguments:
            $playerIndexer: '@api.indexer.players'
            $ladderIndexer: '@api.indexer.ladder'
            $teamIndexer: '@api.indexer.teams'
            $summonerNameIndexer: '@api.indexer.summoner_names'
        tags:
            - { name: kernel.event_subscriber }
